### ISSUE TITLE
Performance VS standard components

### ISSUE THREAD

**Issue by AleDema** [nanxiaobei/react-split-components#5]
Are there any benchmarks to verify the performance difference between RiC and vanilla React components?

**Comment by nanxiaobei** [comment]
It must be better than the standard components, because there is no `deps` diff process.

**Comment by AleDema** [comment]
A benchmark would be a better way to prove this and would entice more devs to use RiCs. You also have another repo with an alternative React DX, that being solid-react, so it'd be nice to know how they both perform compared to each other.
