### ISSUE TITLE
Is there anything that can concretely show this pattern Benchmarks better than standard react?

### ISSUE THREAD

**Issue by duttaoindril** [nanxiaobei/react-split-components#6]
I feel like this is close to solid.js when it comes to what you're promising - the render function with all the logic only runs once, yet the UI is still reactive. The code isn't the most ergonomic, but if it proves to be more performant with such little effort, it'd easily be worth it.

**Comment by nanxiaobei** [comment]
It should be possible to write a demo for implementation, but no similar work has been done.
